replaced travis CI with GHA GI
plus3it/terraform-aws-tardigrade-inspector pull request #179
Opened 2023-01-31 18:54 UTC by johnricords

2023-02-01 18:11 UTC, johnricords commented
tested locally, results:

```
make terraform/pytest PYTEST_ARGS="-v --nomock"
[bootstrap]: Using external tardigrade-ci, skipping auto-init
[pytest//Volumes/Development/tardigrade-ci/tests/terraform_pytest] Starting Python tests found under the directory "/Volumes/Development/tardigrade-ci/tests/terraform_pytest"
pytest /Volumes/Development/tardigrade-ci/tests/terraform_pytest -v --nomock 
================================================ test session starts ================================================
platform darwin -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0 -- /Users/johnricords/.local/opt/python@3.10/bin/python3.10
cachedir: .pytest_cache
rootdir: /Volumes/Development
collected 4 items                                                                                                   

../tardigrade-ci/tests/terraform_pytest/test_terraform_install.py::test_modules[schedule_based] PASSED        [ 25%]
../tardigrade-ci/tests/terraform_pytest/test_terraform_install.py::test_modules[premade_policy] PASSED        [ 50%]
../tardigrade-ci/tests/terraform_pytest/test_terraform_install.py::test_modules[event_and_schedule] PASSED    [ 75%]
../tardigrade-ci/tests/terraform_pytest/test_terraform_install.py::test_modules[event_based] PASSED           [100%]

=========================================== 4 passed in 97.46s (0:01:37) ============================================
[pytest//Volumes/Development/tardigrade-ci/tests/terraform_pytest]: Tests executed!
```

2023-02-10 17:48 UTC, lorengordon requested changes

2023-02-10 17:48 UTC, lorengordon commented on .github/workflows/lint.yml
> +    uses: plus3it/actions-workflows/.github/workflows/lint.yml@41056300ba78d8be98b45f057aea246f8c4f30cf
This is the old SHA, for plus3it/actions-workflows v1.0.0. Please update all these to the SHA for v1.0.1

2023-02-13 19:33 UTC, johnricords commented on .github/workflows/lint.yml
> +    uses: plus3it/actions-workflows/.github/workflows/lint.yml@41056300ba78d8be98b45f057aea246f8c4f30cf
corrected

2023-02-13 20:38 UTC, lorengordon approved these changes
🚀

2023-02-13 20:42 UTC, merged